minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - nuxt
  - '@nuxt/*'
  - oxc-parser
  - '@oxc-parser/*'
  - oxc-minify
  - '@oxc-minify/*'
  - oxc-transform
  - '@oxc-transform/*'
  - '@oxc-project/types'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
