name: release

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup git config
        uses: qoomon/actions--setup-git@v1.1.1
        with:
          user: bot

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Force Set pnpm Registry
        run: pnpm config set registry https://registry.npmjs.org

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Playground prepare
        run: pnpm dev:prepare

      - name: Publish package
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
